name: Purge Cloudflare Cache

on:
  push:
    branches: [main]

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare Cache
        run: |
          curl -s -X POST "https://api.cloudflare.com/client/v4/zones/bc94ec07ca4d8625e7bcb34376fc2f69/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
